### ISSUE TITLE
error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/imgwarp.cpp:1934: error: (-215:Assertion failed) 

### ISSUE THREAD

**Issue by ProGamerGov** [sunset1995/py360convert#42]
I was trying to measure the library speed and came across this issue while using Colab:

```
# Setup
!git clone https://github.com/sunset1995/py360convert
%cd py360convert
!pip install .
%cd ..
```

Reproducible code:

```
import cv2
import numpy as np

print("OpenCV version:", cv2.__version__)

import py360convert

def test_code():
    face_w = 256
    num_channels = 3
    e_img = np.random.rand(face_w * 2, face_w * 4, num_channels).astype(np.float32)
    fov_deg = 90.0
    h_deg = 50.0
    v_deg = 120.0
    out_hw = (512, 512)
    in_rot_deg = 10.0
    mode = "bilinear"
    
    e2p_result = py360convert.e2p(e_img, fov_deg, h_deg, v_deg, out_hw, in_rot_deg, mode)

test_code()
```

This is the output of the above code:

```
OpenCV version: 4.10.0
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
[<ipython-input-4-9827312756ff>](https://localhost:8080/#) in <cell line: 21>()
     19     e2p_result = py360convert.e2p(e_img, fov_deg, h_deg, v_deg, out_hw, in_rot_deg, mode)
     20 
---> 21 test_code()

2 frames
[<ipython-input-4-9827312756ff>](https://localhost:8080/#) in test_code()
     17     mode = "bilinear"
     18 
---> 19     e2p_result = py360convert.e2p(e_img, fov_deg, h_deg, v_deg, out_hw, in_rot_deg, mode)
     20 
     21 test_code()

[/usr/local/lib/python3.10/dist-packages/py360convert/e2p.py](https://localhost:8080/#) in e2p(e_img, fov_deg, u_deg, v_deg, out_hw, in_rot_deg, mode)
     74     coor_x, coor_y = uv2coor(u, v, h, w)
     75 
---> 76     sampler = EquirecSampler(coor_x, coor_y, order)
     77     pers_img = np.stack([sampler(e_img[..., i]) for i in range(e_img.shape[2])], axis=-1)
     78 

[/usr/local/lib/python3.10/dist-packages/py360convert/utils.py](https://localhost:8080/#) in __init__(self, coor_x, coor_y, order)
    348                 raise NotImplementedError
    349 
--> 350             self._coor_x, self._coor_y = cv2.convertMaps(
    351                 coor_x,
    352                 coor_y,

error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/imgwarp.cpp:1934: error: (-215:Assertion failed) (m1type == CV_16SC2 && (nninterpolate || m2type == CV_16UC1 || m2type == CV_16SC1)) || (m2type == CV_16SC2 && (nninterpolate || m1type == CV_16UC1 || m1type == CV_16SC1)) || (m1type == CV_32FC1 && m2type == CV_32FC1) || (m1type == CV_32FC2 && m2->empty()) in function 'convertMaps'
```

**Comment by BrianPugh** [comment]
This was fixed [here](https://github.com/sunset1995/py360convert/commit/1382e987d33422176fe8d2477d33fec0ba4c3987#diff-7b5278f2d87b03307a1d12db7a4207c3cf739128a26dbc27bf01841f7d0156c5R245). Thanks for reporting!

**Comment by ProGamerGov** [comment]
@BrianPugh The issue still remains if you use np.float16 or np.float64

**Comment by BrianPugh** [comment]
Fixed in v1.0.1!
